.ORIG x3000
	LEA R1, HELLO
AGAIN	LDR R2, R1, #0
	BRz NEXT
	ADD R1 ,R1 ,#1
	BR AGAIN
NEXT	LEA R0 ,PROMPT
	TRAP x22	; PUTS
	ADD R3, R3, #-10; (A)
AGAIN2	TRAP x20	; GETC
	TRAP x21	; OUT
	ADD R2, R0, R3
	BRz CONT
	STR R0, R1, #0	; (B)
	ADD R1, R1, #1	; (C)
	BR AGAIN2
CONT	AND R2, R2, #0
	STR R2, R1, #0	; (D)
	LEA R0, HELLO
	TRAP x22	; PUTS
	TRAP x25	; HALT
NEGENTER .FILL xFFF6	; -x0A
PROMPT	.STRINGZ "Please enter your name: "
HELLO	.STRINGZ "Hello, "
	.BLKW       #25
	.END